### ISSUE TITLE
Bookshelf list resets when changing tabs

### ISSUE THREAD

**Issue by Grunthos** [eleybourn/Book-Catalogue#523]
From a user:

> Have noticed an issue tonight - when adding a magazine manually, I enter the details, change the bookshelf, go to the notes tab and add a location, then when I go back to the details tab the bookshelf has switched back to the default.  Am I doing something wrong?

When returning from bookshelf dialog, need to save details in the master data copy.

NB: should confirm that data is saved for other dialogs (series & authors).

**Comment by daniele-athome** [comment]
I took a quick look at the code (like 5 mins) and it seems that the app restores the default values because the fragment's onResume always reload the book data, am I right?

**Comment by Grunthos** [comment]
I think/hope not. I expect it relates to that tho: I expect it is not saving *all* the data in the onPause, which is what it is supposed to do...

**Comment by daniele-athome** [comment]
Ok, if you need help testing or something, you can ask to me - I've an Android Studio environment with your project installed and ready. Unfortunately, however, I can't actively write code at the moment, sorry.

**Comment by Grunthos** [comment]
Looking more closely, the code that loads bookshelves from the saved copy overwrites it before loading...will fix.

**Comment by Grunthos** [comment]
This has been addressed in the latest beta on Google Play; please check if possible.

**Comment by daniele-athome** [comment]
I can confirm it works.
