### ISSUE TITLE
December is short a day

### ISSUE THREAD

**Issue by avarisclari** [eleybourn/Book-Catalogue#644]
Was putting a book I recently read in, and I started on Dec 31. The app only goes to 30 for some reason. I'm looking through the code to find where this is so I can help fix it, this is just a notification.

Edit:
Alright, this is a weird one for me. December isn't short a day if you select it. If you press minus to go from Jan to Dec then it is. I don't know what's causing it, but I'll look more. Sorry for any trouble.

**Comment by Grunthos** [comment]
Very odd. I don't see this behaviour.

Can you send a screen shot? And go to "Help"->"Send Information" so we get info 
about your environment?

**Comment by avarisclari** [comment]
![2015_01_05_21 26 21](https://cloud.githubusercontent.com/assets/3046491/5623429/16feeeae-9522-11e4-8218-0cae6590535d.png)
Sent the information as well. The bug moved to January this time.

**Comment by avarisclari** [comment]
I don't know, I just realized there was an update and it fixed this. I can't replicate it anymore. I'll just close this for now, and if it appears again, I'll take another look.

**Comment by Grunthos** [comment]
Two questions:

1. (just checking) Did you try to scroll the list up futher? It *should* scroll to 31...

2. What happens if you are on 30 and press the "+" button?

**Comment by Grunthos** [comment]
Next time it happens, try to remember the sequence of events. It's probably a subtle sequence...like pressing a "next" key, or using arrows etc

**Comment by avarisclari** [comment]
1) yes I did, when the bug would occur it would stop at 30
2) it would just sit there and not go to -- or 31

If it occurs again, I'll do my best to figure out what's causing it. Again, sorry for any inconvenience.

**Comment by avarisclari** [comment]
Well, I managed to duplicate it again haha. Umm... Testing it to figure out what's causing it. It seems to be scrolling through months too quickly and going back to a 31 will do it.

**Comment by avarisclari** [comment]
Yeah, if you set it to 31 and go to a 30 month, you can't go back to 31 for some reason.

**Comment by Grunthos** [comment]
On 6/01/2015 5:42 PM, Christopher Weigle wrote:
> Yeah, if you set it to 31 and go to a 30 month, you can't go back to 31 for 
> some reason.

Thanks for this; it's fixed in the next release

**Comment by Grunthos** [comment]
Fixed in 5.1.2
