### ISSUE TITLE
Android Studio support

### ISSUE THREAD

**Issue by silin** [eleybourn/Book-Catalogue#648]
Add ability to build project under Android Studio
This can help to involve more developers who prefer to work in this IDE
I`ve already have all needed Gradle build scripts, so I can push them soon

**Comment by Grunthos** [comment]
That would be FANTASTIC! I installed AS, but had problems getting BC to work with it (build errors regarding API versions...despite the API versions being present in the SDK)...and gave up.

My mistake may have been using the installer without the SDK, but I would like to run Eclipse along side it, so that seems prudent.

Once you have it going, I'd love to do the same.

**Comment by david-bakin** [comment]
I was just going to ask about this!  I have an addition I've been longing to make and finally have time for working on it.  But I'd prefer to use the supported Android Studio (for its similarities to IntelliJ) rather than Eclipse (which I never much liked).

**Comment by silin** [comment]
OK, good. I will create pull request today: 
 - Gradle build script;
 - needed Gradle files;
 - build instructions.

**Comment by Grunthos** [comment]
Wonderful! I will see if I can build it, and let you know what fails for me.

**Comment by silin** [comment]
Additionally advantage that can be simply reached with Android Studio is adding of third-party configuration classes to local properties (I mean for such classes that must be added to project to support Amazon and Goodreads - with API keys). In this case other developers do not need to create their own classes with API keys for Amazon and Goodreads to build project in DEBUG. Because it is not possible to build the project without adding of some stub classes with above API constants. And it is not very convenient, because these file should not be added to repository and we always must control them to do not occasionally add to sources.

But it is not very hard with Gradle to do that for DEBUG buidls we do not need this constants and only need them for RELEASE builds

**Comment by Grunthos** [comment]
Does that mean it just ignores the missing files? Or is there a way to have different files for DEBUG vs RELEASE builds?

**Comment by silin** [comment]
There is/are simple way/ways to have different files (not sure that files is the best option)/ fields / properties for DEBUG/RELEASE
