### ISSUE TITLE
cross-feed and/or cross-check 10 and 13 digits ISBN

### ISSUE THREAD

**Issue by autostar** [eleybourn/Book-Catalogue#649]
Most books have both 13- and 10-digit ISBNs, but BookCat does not notice duplicates if one was entered as 10-digit and the second was entered as 13 (or vice versa).

Use case: i tend to key in ISBNs manually, since i'm faster than the scanner process, and the scanner process mis-fills (or requires painful override for things like shelves and anthology keys).  It's easier for me to do the 10-digit ;-).

Possibly the best win would be for a user-option for  either form of ISBN entry to fill "both" fields (i realize that it's probably currently a single field, and possibly the primary key), or for BookCat to "fake" the 2nd form.

thanks
--richard  seymour

**Comment by Grunthos** [comment]
Fixed in current sources. Now checks for both.

**Comment by autostar** [comment]
thank you! ... now for the next one...
