### ISSUE TITLE
ISBN scanning not working in v5.1.2

### ISSUE THREAD

**Issue by kaitiriwa** [eleybourn/Book-Catalogue#656]
Have used Book Catalogue on MotoG LTE running KitKat 4.4. After upgrading to v5.1.2, ISBN scanning no longer works. Screen flashes white briefly as though camera is starting, and then returns to Book Catalogue main screen. MotoG camera is working as usual in other apps.

**Comment by Grunthos** [comment]
Try installing one of the recommended scanner apps: ZXing or pic2shop , and send us an email if if does not work.

**Comment by kaitiriwa** [comment]
Installed zxing and everything is working again. Many thanks FP the prompt
response.
