### ISSUE TITLE
Authorize Goodreads 

### ISSUE THREAD

**Issue by fazen** [eleybourn/Book-Catalogue#675]
I'm trying to authorize goodreads in Book Catalogue.
I have a Galaxy S5 with Android 5.0 and Firefox for Android as default browser.
I registered and logged to goodreads in the browser **and** in the Goodreads App I installed.
Clicking the button "Authorize Access" in Book Catalogue give me this error: "There was a network problem while accessing goodreads..."

- Android 5.0
- Firefox 39.0
- Book Catalogue 5.07
- Goodreads 1.14.4

**Comment by Grunthos** [comment]
See our fAQ:

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-%28FAQ%29

**Comment by fazen** [comment]
After uninstalling and reinstalling Book Catalogue App, it worked.
