### ISSUE TITLE
SD card accidently erased

### ISSUE THREAD

**Issue by thefrazzledmama** [eleybourn/Book-Catalogue#684]
But I was able to recover a file called com.eleybourn.bookcatalogue-1.asec.  Is this file going to help me at all or is that the app programming?

Thanks,
Margaret

**Comment by Grunthos** [comment]
On 19/08/2015 8:16 AM, thefrazzledmama wrote:
> But I was able to recover a file called com.eleybourn.bookcatalogue-1.asec. Is 
> this file going to help me at all or is that the app programming?

You need a recent archive (.bcbk) or an export (.csv) file I am afraid.

**Comment by thefrazzledmama** [comment]
Okay, thank you
