### ISSUE TITLE
Maximum number of books

### ISSUE THREAD

**Issue by BecksideBooks** [eleybourn/Book-Catalogue#689]
Hi
I'm planning on using your app for a relatively straightforward way of uploading a number of books in my small secondhand bookshop to my Amazon seller account via the BookLoader inventory spreadsheet (to save me A LOT of typing!).
I was just wondering if there is a maximum number of books / entries that your app supports, both in terms of the app itself and in the export file? Ideally I will be able to use it to inventory my entire Amazon stock at once, which may be up to around 10,000 books. If it won't support this number then I will have to export the data to a different piece of inventory management software before  exporting to Amazon. That will be fine (just take a bit longer), but I just need to know before I start!
Thanks
Krystl
PS - perhaps you should consider having an alternative export option where the format matches the format required by amazon - I would happily pay a reasonable amount for this! There are very few free book inventory management software out there and it can be quite awkward to convert to Amazon format. Also, none of them (that I have found so far) include an app with a barcode scanner.

**Comment by Grunthos** [comment]
No limit, except the speed, memory and storage of the device you use. We have users with thousands of books. Would be interested for future users what you end up using, how many books you have and how you find the performance.

**Comment by BecksideBooks** [comment]
Great, it'll be a few months before i give it a good test drive but i'll let you know how it goes.
