### ISSUE TITLE
Anthology info -- SOME not exporting

### ISSUE THREAD

**Issue by asaulnier27** [eleybourn/Book-Catalogue#691]
I enjoy your app on my Nexus 7 and want to port the data to a Samsung Galaxy Tab S2. I'm having trouble exporting anthology details for some of my books. I can't determine what conditions are causing some of the anthologies to lose the anthology details upon export while others retain theirs. Is there a length limit or limit to characters that can be used? I have tried exporting via archiving the database and also via a CSV export.

Thank you for your help!

**Comment by Grunthos** [comment]
This is odd. There are no limitations that I am aware of.

Are the same ones always missing?

How did you confirm that they are missing?

**Comment by asaulnier27** [comment]
Thank you for your prompt reply.

The anthology info is still there in the original file on my Nexus but does
not appear when I export via archive or CSV and then import either type
into Book Catalogue on my Galaxy. I then checked the exported CSV file for
a few books that SHOULD have had anthology details (from anthology titles
screen) and it wasn't in the anthology_titles column of CSV file for some
but was for others.

I used characters like 😃😇⭐🔥()#= in some of the ratings I entered as part
of anthology titles. The problem was NOT limited to using characters like
😃😇⭐🔥, though as at least some books with missing anthology title info in
the CSV and imported archive files only had letters, numbers, and
characters like ()#= in the anthology titles I had entered.

Let me know if you need additional information from me.

Best regards.

**Comment by Grunthos** [comment]
OK, can you go to the source device and:

- run 'export to CSV'
- go to 'Admin & Prefs' and select 'Copy Database' (near the end of the list)
- go to 'Help'->'Send Information' and send the resulting email. It's probably wise to add a reference to this bug in the subject

Hopefully we can understand the problem a little better with these details.

**Comment by Grunthos** [comment]
Fixed in 5.2.1-Beta
