### ISSUE TITLE
Enter All Possible ISBN / ASIN

### ISSUE THREAD

**Issue by vrajs5** [eleybourn/Book-Catalogue#702]
Currently app adds only one of the book code from ISBN-10, ISBN-13 or ASIN. There should be option to enter all possible codes so that while synchronizing with Goodread or Librarything it will find maximum number of books.

**Comment by Grunthos** [comment]
This is probably a less useful idea since it results in, theoretically, everyone entering multiple ISBNs for every book, and still not getting a search result that they want. 

A much better outcome could be achieved by getting goodreads to return other editions of a book based on an ISBN search.
