### ISSUE TITLE
Duplicate entries in translations

### ISSUE THREAD

**Issue by GuillaumeSmaha** [eleybourn/Book-Catalogue#703]
I can't build the last version 5.2.0 because there few duplicate entries.

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':mergeDebugResources'.
    > Error: Found item String/translators_blurb more than one time
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

In res/values-de/string.xml and res/values-nl/string.xml:
- translators_blurb
- install_scan

**Comment by Grunthos** [comment]
Fixed in current repo
