### ISSUE TITLE
How to retrieve covers

### ISSUE THREAD

**Issue by tomas08205** [eleybourn/Book-Catalogue#707]
I had to replace my smartphone. I exported book catalogue to csv file. How do I get it all back, including covers, on new device?

**Comment by Grunthos** [comment]
On 20-Nov-15 12:00, tomas08205 wrote:
> I had to replace my smartphone. I exported book catalogue to csv file. How do 
> I get it all back, including covers, on new device?


See our FAQ:

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-%28FAQ%29
