### ISSUE TITLE
Adding image url in the CSV file

### ISSUE THREAD

**Issue by tchierry94** [eleybourn/Book-Catalogue#715]
This is a wonderful app. I was looking for someone to build such an app that will help me to build up a db but here it is! 

This app stands out for 2 major reasons
1. It retrieves the book description! and
2. the book cover; 
the main things that users in a library would pay attention in a db, aside the lookups function of other info.

The only thing I would need would be to add the image url in the CSV file.

The problem right is that
1. It is impossible to have the book cover outside the app. There's no app to retrieve data from .bkbc
2. I have to to still add image to the added books one by one or to find and add the relevant image url to each book.

The only way to solve that would be to add a column for image url for each book in the CSV. You already have fetched the url to get the cover. According to me, this would make the app perfect

**Comment by Grunthos** [comment]
Unfortunately this is not possible; the URL is (in most cases) provided after logging in to an API and is not or may not be generally available. We use the URL to copy it at the time the book is added/edited.
