### ISSUE TITLE
Make auto-capitalization optional

### ISSUE THREAD

**Issue by ogregoire** [eleybourn/Book-Catalogue#717]
The application in its current form considers only the English language when it comes to book title capitalization.

In French, the capitalization of titles is totally different and the rules are really complex (it depends on the kind of title: is it a sentence or just words, what words are used, the order of the words, etc.).

Most of the time, Amazon and friends get those correct but the application tries its best by applying the English language rule which forces me to manually (and painfully) edit every single title. Also, when editing a title, the application forces me in a "capitalizing" keyboard, which is painful because I most often have to uncapitalize letters, forcing me to select the letter, remove capitalization then rewrite the letter.

The rules for capitalization in French are complex and I don't expect an application to get them right without proper French semantic analysis. The English Wikipedia has a summary of how [French titles should be capitalized](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/France_and_French-related#Capitalization). Yet it doesn't cover everything, which is actually a kind of compromise, and [more covered on the French Wikipedia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Titres_d.27.C5.93uvres_.28livres.2C_films.2C_etc..29). Therefore I'm not asking that you implement the titles under those rules for French titles, but rather make the English rules optional to follow what the book sources provided.

So, concretely, please make these two functionalities (auto-capitalization and capitalizing keyboard) optional under a preference.

**Comment by daniele-athome** [comment]
+1. I suggest using the locale settings of the book's language (if set), or fallback to the current system locale. I think setting a correct inputType might work (I don't know about how it can be linked to a custom locale though).

**Comment by ogregoire** [comment]
Well, there might be more options like the one you suggest, but I would really love to get the capitalization as provided by the source.

Let's not forget that optionally remove the capitalizing keyboard is part of my request as well.

**Comment by daniele-athome** [comment]
Sure, sorry I was talking about the user writing the title manually. But of course the automatic title should use the API exact string.

**Comment by silin** [comment]
Same problem for Russian language

**Comment by Grunthos** [comment]
As of the current beta, fr and de are no longer capitalized on editing. The data provided by the source should not be mangled either.

It sounds like we should add ru to the list. 

Are there other languages that should not be capitalised?

The options we have are: no capitalization, capitalise sentences, and capitalise words. We use the last option by default and, currently in beta, the first option for FR and DE.

**Comment by daniele-athome** [comment]
Italian please.

**Comment by Grunthos** [comment]
OK, Italian and Russian. IIRC, I separated the styles for author names, book titles and series titles.

Should they all be "no capitalization", or just the titles?

**Comment by daniele-athome** [comment]
At least for Italian, the "no caps" rule should be applied to book titles and series titles.

**Comment by ogregoire** [comment]
@Grunthos What do you mean by "no capitalization"? That the title from the source doesn't go through the capitalization process or that it goes through a process that "uncapitalizes" it?

Also, what about the keyboard, can this be implemented as part of the same option?

**Comment by daniele-athome** [comment]
@Grunthos when I said "no caps" I meant only the first letter should be uppercase.

**Comment by Grunthos** [comment]
@ogregoire The source data (from google/goodreads etc) isn't being modified by the current search process....that is my belief at least! I could be wrong. My belief is that the editing process does the capitalization. The changes in the latest beta allow for per-locale settings for the editing; specifically, we can force words or sentences to be capitalized, or just leave them as the user set them. Unfortunately this is not set per-book, but for the app.

So, the summary so far (please correct me if I am wrong):

IT: Capitalize first word in title and series; capitalize all words in author names
RU: ?
FR: leave everything exactly how the user types it.

**Comment by daniele-athome** [comment]
:+1: for Italian. Thanks!

**Comment by ogregoire** [comment]
I didn't think about authors: only about book titles. Since you offer the choice, please leave the title as free as possible. The author names should have all the words capitalized (ex: "Duchemin", not "DUCHEMIN" or "duchemin").

General rule for French:
* capitalize people (author) names;
* leave the rest as entered.

**Comment by daniele-athome** [comment]
The issue with book and title series is that sometimes APIs return all caps, sometimes all lowercase, so it's hard to choose a fixed rule for all books (e.g. what if there is a proper name inside a title that should be capitalized and the API gives you all caps?). So I suggest leaving the data from API unaltered and apply these rules only to user input. What do you think guys?

**Comment by Grunthos** [comment]
@daniele-athome :
> So I suggest leaving the data from API unaltered and apply these rules only to user input. What do you think guys?

That's what *should* be happening now...though I guess I should check that.

**Comment by daniele-athome** [comment]
I remember having one or two books with all capitals in the title. I can't remember which one though, I have to look for it.

**Comment by Grunthos** [comment]
IT: Capitalize first WORD in title and series; capitalise proper names
RU: ? Not sure, but will  capitalise proper names;  leave title and series as entered
FR: capitalise proper names; leave title and series as entered

**Comment by Grunthos** [comment]
This has been addressed in the latest beta on Google Play; please check if possible.

**Comment by ogregoire** [comment]
Thank you! However how can I find the "latest beta on Google Play"? I see only [instructions for an "offline" beta version](https://github.com/eleybourn/Book-Catalogue/blob/master/beta_instructions.txt), but no APK. and I couldn't find anything with the search "Book Catalogue Beta".

**Comment by Grunthos** [comment]
I think this URL should get you into the beta programme:

    https://play.google.com/apps/testing/com.eleybourn.bookcatalogue

**Comment by ogregoire** [comment]
Okay, so I registered on that link (thank you for it, btw), then my application got updated and I see version "5.2.0" in the about box and I properly have it since I see the changes I PR'd in #718.

For French, I see the following:
* The title edition doesn't force me into English case, so that's already a great win!
* However upon import, the title is still "English cased".

In my example, I selected the book with ISBN 2070643026.
* On Amazon, the title is *Harry Potter, I : Harry Potter à l'école des sorciers* (the case is OK for French, when editing, I should only remove the series+number part, that's minor, but OK)
* On Google Books, the title is *Harry Potter à l’École des Sorciers* (case is not OK for French, when editing, nearly all will have to be rewritten)
* On Goodreads, the title is *Harry Potter à l'école des sorciers* (entirely correct)

Book Catalogue offered me none of the above titles as is, but it offered me *Harry Potter À L'école Des Sorciers* instead. So I see two possibilities:
* the title went through the English-casing function, or
* another source was used. In that case, which one is it so I can compare?

**Comment by Grunthos** [comment]
On 20-Jan-16 01:16, Olivier Grégoire wrote:
> On Amazon, the title is /Harry Potter, I : Harry Potter à l'école des 
> sorciers/ (the case is OK for French, when editing, I should only remove the 
> series+number part, that's minor, but OK)

Short version: you are correct, we mess with the case of titles in the code that 
gets the data. This will be fixed.

Long version:

The tricky and annoying this here is that we use Amazon *US* for searches. We 
are in the process of trying to use locale-specific Amazon sites when possible, 
but it's not done yet.

Amazon US return two:
     Harry Potter A L'Ecole des Sorciers (French Edition)
     Harry Potter a L'ecole Des Sorciers

Amazon FR returns three books:
     Harry Potter, I : Harry Potter à l'école des sorciers
     Harry Potter A L'Ecole des Sorciers (French Edition)
     (HARRY POTTER A L'ECOLE DES SORCIERS) BY Rowling, J. K.(Author)Paperback on 
(09 , 2011)

Interestingly, goodreads returns:

     Harry Potter à l'école des sorciers

AND is deemed by us to be the most trustworthy, so would be correct if we didn't 
mess with it.

In the longer term we are not guaranteed that we will get the right text from 
US-based goodreads, and maybe we should allow regional Amazon to overrule all 
others...

**Comment by Grunthos** [comment]
In the short-to-long term, I have removed the call to 'proper case' text, and the code that does proper-casing to avoid the temptation to use it in the future.

New APK in beta uploaded. Should percolate through according in google-time.

Let me know how you go!

**Comment by ogregoire** [comment]
Okay, I confirm it's now OK. I don't know which source was used (Goodreads, most likely), but the case is as I expect for a French book and the English casing wasn't applied.
