### ISSUE TITLE
Latest beta fails at startup

### ISSUE THREAD

**Issue by ogregoire** [eleybourn/Book-Catalogue#722]
The latest beta version fails at launch with a class not found exception in `dalvik.system.BaseDexClassLoader`, trying to locate `com.eleybourn.bookcatalogue.BookCatalogueApp`.

I tried to reinstall the beta version from Google Play beta, but I still get the same issue.

**Comment by Grunthos** [comment]
Pulled from store, investigating

**Comment by Grunthos** [comment]
Confirmed. Fixed by rebuild. New version uploaded. Also available here:

**Comment by Grunthos** [comment]
APK can also be found here:

    https://github.com/eleybourn/Book-Catalogue/releases/tag/v5.2.0-RC3a
