### ISSUE TITLE
Bugs with new "read" bookshelf: duplicated books, lost old category info ...

### ISSUE THREAD

**Issue by gmnenad** [eleybourn/Book-Catalogue#726]
I just noticed that (probably after update of app) I got several new bookshelves, like "read", "to-read' and "currently-reading" , where I did not define any of those.

Problem is that resulted in two severe bugs:
1) many of my books are duplicated, mostly with new "read" bookshelf -  while original copy still exists with original bookshelf. 
2) even worse, some books are not duplicated but have instead lost original bookshelf and now only have new "read" one (with green check sign next to them in list)

Some duplicates do not have picture , and have different name (for example, still have "The" in name, that I usually delete) - so I wonder if that was not some failed attempt to sync with Goodreads.

I noticed problem just now, but after trying to restore backups I saw that problem exists even in my backup from 29.Jan, but not in backup from December. That is why I suspected update from 20th January, although this looks more like failed Goodreads sync attempt - ie like Goodread sync can duplicate books and add bookshelves.

BTW, sorry if this was not right place to report bug, could not find any other suitable one ;p

**Comment by Shadouw** [comment]
Goodreads uses these shelves to track the "read" flag. Seems to be incompatible to the BookCatalogue flag.

**Comment by Grunthos** [comment]
We try to sync the 'read/to-read' shelves etc, but goodreads treats some of these as exclusive (cant be on both), for no good reason at all.

Any other shelves that appeared are likely because they were in goodreads.

A book can be on more than one shelf (think of them as keywords).

If there are genuinely duplicated books, it is probably because they don't have ISBNs and a local match could not be found. It should be safe to delete the 'non-goodreads' version.

**Comment by gmnenad** [comment]
Thanks, but deleting "non-goodreads" versions is not viable solution:
- it is hard to find dozens of duplicates among hundreds of books
- goodreads versions are inferior, lacking any changes I made previously like name changes, serials and, most importantly, shelves that I used on that book

Since goodreads version lose those important things, only viable solution would be to delete goodreads duplicates. But problem remains on cases where you managed to join two books but where you kept goodreads info, which as described above is not good.

You are probably correct about reason - I often add books with "search by name" instead of entering ISBN, and I often change title name (to remove "The"), and change series name (to keep only one common with other books in that series). So it will not match generic ISBN data for that book. But , on the other hand, I initially populated goodreads with those books from BookCatalogue, so they should be matching.

In any case, my current "workaround" was to use old backup, reenter newer books, and stop using goodreads sync. In general, if this bug will stop other users from using goodreads sync, maybe it should not be closed. One suggestion would be to have option for "one-way" sync with goodreads, where you only update list t here, but do not touch BookCatalogue - for us who use BookCatalogue as primary list.

**Comment by Grunthos** [comment]
OK; another option:

- be cautious: run a backup to archive
- export to CSV; copy file to desktop
- edit the CSV *BUT MAKE SURE TO IMPORT ALL FIELDS AS TEXT!*
- sort by title /author to find the dups
- copy the goodreads id field from the goodreads rows to the rows of the records 
for one(s) you want to keep -- the goodreads id *should* be blank in them!
- change the author of the one(s) you want to delete to something like 'AAA, 
DELETE ME'
- copy the CSV file back
- 'Import from CSV'
- delete all books under the author specified above

Ideally we should provide a 'merge books' option, but it's just a matter of 
available time
