### ISSUE TITLE
Exporting datas to Book Collector

### ISSUE THREAD

**Issue by Boncurek84** [eleybourn/Book-Catalogue#727]
Hello, 
Can you develop exporting feature? It will be useful to transfer book data to Book Collector via .csv file. 
The problem is that Book Collector from www.collectorz.com recognize only 3 fields:
ISBN, Title and Author:
http://www.collectorz.com/book/manual/win/v15/en/topic/importing-from-text
Users should have options which datas are saved to csv file,

**Comment by Grunthos** [comment]
Out export format is documented in out wiki, and it is probably better for the Book Collector people to develop an importer than for us to develop an exporter.
