### ISSUE TITLE
Cannot load cover images in non-edit screen

### ISSUE THREAD

**Issue by icarius22** [eleybourn/Book-Catalogue#743]
Hi:
It doesn´t load the cover image in the non-edit screen. The cover image appears in the edit screen.
Thank you

**Comment by icarius22** [comment]
When the cover image has horizontal orientation, it appears in both screens (non-edit and edit). When the cover has vertical orientation it disappears from non-edit screen. 
I have a Samsung S5. Yesterday, the app worked fine, but I update the cellphone and now I have this problem.

**Comment by eleybourn** [comment]
I confirm that I can see images in all and only rectangular books.  

I have so far checked that I cannot see any images in any books except... in so far about 30 books (bandes dessinées) in approximately 6 different collections, and in all rectangular books, and in "only" all rectangular books! 

I suggest that the size of the book has something to do with our problem.

**Comment by Grunthos** [comment]
No that I have Marshmallow, I can reproduce it also...will investigate more thoroughly.

**Comment by icarius22** [comment]
Issue solved
