### ISSUE TITLE
New phone - restore database

### ISSUE THREAD

**Issue by Dianaperry12** [eleybourn/Book-Catalogue#755]
I was able to copy the entire book catalog directory from my old phone to my PC.   The old phone didn't have an SD card.   I then copied it to my new phone (which does have an SD card), but it can't find it.   I also tried to export the database to .csv from the old phone, and sent it via email (only option).   I saved it to my PC (just in case) and also opened my email from my new phone and downloaded it.   I open book catalogue and used the 'import from .csv' function.   Although it says it imported it, there are no books in my library.     I just want it to work on my new phone without entering every book by hand again.

Thanks!   Diana Perry  - dianaperry12@gmail.com

**Comment by Grunthos** [comment]
Have a look at our FAQ for copying to a new phone:

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by Grunthos** [comment]
Version 6 revamps backup/restore.
