### ISSUE TITLE
Problems with Amazon lookups?

### ISSUE THREAD

**Issue by autostar** [eleybourn/Book-Catalogue#756]
Recently when i add an ISBN, a pop-up appears that says:
"Search failed while searching Amazon: no data found for 0960330208//"
(frequently followed by the catalog entry form having no pre-filled data beyond the ISBN)
((the above example ISBN fared even worse... the pre-filled was for entirely the wrong book, except for the title ... if i browser-search amazon with that ISBN, i get the correct book))

Has amazon changed their request format, or am i simply seeing "holiday overload" of their servers?
(BookCatalogue version 5.2.0 on Android 4.3)

**Comment by rstwhile** [comment]
I am also having the above problem.  Can't be "holiday overload" as this is not the first time it has happened.  Seemed to be solved after a week or so but is now back again

**Comment by eleybourn** [comment]
My bad. Sorry. I was updating the code for my blog and accidentally broke the amazon lookup function.

**Comment by eleybourn** [comment]
I'm going to make a change and move the amazon lookup to its own subdomain so this doesn't happen again.
