### ISSUE TITLE
Import from CSV

### ISSUE THREAD

**Issue by boolsea** [eleybourn/Book-Catalogue#759]
Hello,
Firstly, thanks for this software. It works well.

I have a lot of Ebooks and I wanted to import them into my catalogue so I wrote some software to extract data from each Ebook and build a csv file for import.

I formatted the csv file as your documentation said, but it would not import all my books, it seemed to stop after around 200 or so books.

So I exported my existing books to a CSV file, checked the format and found that there is an extra field 'language' (after "genre") that doesn't appear in the documentation.

Even after adding this field to my csv file, it seems that I can't get some books to import. It still seems to stop after about 200 books or so (I'm importing around 600 books in one csv file).

The most likely cause is that there is an issue with my CSV file format (I'm still looking at it).

My questions are:
1) Is there a limit to the number of books that can be imported from a csv file?
2) Is there a way I can quickly delete all books in the database leaving all other data untouched (author/genre/bookshelves etc)? So far I've uninstalled, re-installed and recovered a backup, this seems to do it but it's a bit drastic.

My best regards, Andrew Bools.

**Comment by Grunthos** [comment]
1. No
2. No. But re-importing the books will recreate the bookshelves you had them on. Best way to delete all books is uninstall/reinstall

After an import fails, go to 'Help'->'Send Information' and we may be able to assist.

**Comment by boolsea** [comment]
Thanks Grunthos, that was quick!

I'll look at my csv file for a little longer.  If there's no limit to the number of books I can import, then I'm 99% sure it's an issue with my csv file format.

If I can't see it, I'll do as you suggest.

Thanks again.
Regards,
Andrew.

**Comment by boolsea** [comment]
Hello Grunthos,

I was correct, it was my issue  HHIS (hangs head in shame).  I had a title with a " in it and didn't escape it in the CSV file, and as a bonus, I didn't spot it when I looked at the file contents.

It's always the 'easy' problems that catch you out.

Thanks for your help.

Regards,
Andrew.
