### ISSUE TITLE
Transferring data to a new device.

### ISSUE THREAD

**Issue by MelissaKline** [eleybourn/Book-Catalogue#760]
I'm having trouble transferring my data from Book Catalogue to a new device.  I'm going from a Samsung Galaxy to a Motorola.  I've tried syncing the phones through my google account.  I've tried backing it up to an sd card, but it doesn't work.  Any suggestions would be appreciated.

**Comment by eleybourn** [comment]
Hi Melissa, 

Have you had a look at the FAQ here - https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-backuprestoreexport-my-catalogue-to-a-new-phone

Have a go at those instructions and let us know if you have any issues. 

Cheers
Evan

**Comment by MelissaKline** [comment]
Hi Evan,
I can move Book Catalogue to the sd card, but it won't let me back it up to an archive on an sd card.  I've saved other apps to this sd card with no problems and I know it has enough space.   
Any suggestions for another way to do this?
Thanks!Melissa

**Comment by eleybourn** [comment]
We'll continue this conversation over email.
