### ISSUE TITLE
Make as read from long press

### ISSUE THREAD

**Issue by eleybourn** [eleybourn/Book-Catalogue#770]
Via Email: 

An improvement function request...it would be really nice to have the ability to mark the book read without having to go all the way into the edit mode and further down. If this could be checked from the long-press function, that would be really great. It would also be nice to see that indication in the main detail page or even on the bookshelf page in same way. The way it is currently I will unlikely use that function just because it takes too long to get to, but I would really like to if it was easier.

**Comment by nstouls** [comment]
#732 Make as read from long press

**Comment by Grunthos** [comment]
This has been included in next release. Thank you!
