### ISSUE TITLE
Feature request: move/add multiple books to a new bookshelf

### ISSUE THREAD

**Issue by tarrynz** [eleybourn/Book-Catalogue#772]
Hi
Love the app, it has saved me from carrying around reams of paper lists, and aided my need for organisation and keeping lists of everything. I have been using it for many years now, and I recommend it to everyone I can. I even keep all my music and dvds on it.

Is there any chance you could add a feature to move or add multiple books to a new bookshelf? Like the way android lets you select pictures/files and move them to new locations. But you might just want to add to a new shelf, not move.

I was quite extensive when settings up my bookshelves,  but if I should decide on a new organisation system, it would mean editing each book individually, and while I am sure there are plenty of people out there with many more items than me, it would still take a considerable amount of time as I have almost 3000 items. 
Thanks!

**Comment by Grunthos** [comment]
Hi,
Thanks for the suggestion, this is already on our to-do list:

https://github.com/eleybourn/Book-Catalogue/issues/265
