### ISSUE TITLE
Book Catalogue . . . Transferring csv file from email to new phone 

### ISSUE THREAD

**Issue by MelissaKline** [eleybourn/Book-Catalogue#773]
I have saved a backup of my book list (csv file) and sent it to my e-mail.  Now, how do I get that data into the Book Catalogue app on a new android phone?  Thanks so much.

**Comment by dresdengirl** [comment]
Did you find a solution to this problem? I am trying to do the same thing and can't figure out how.

**Comment by Grunthos** [comment]
Please see our FAQ:

    https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by MelissaKline** [comment]
I've tried everything on the page numerous times. I had 500+ books in my file.  It would only transfer 360 of them. I finally copied them over to Good Reads.  I'll be using that from now on.  Great little app if it would have transferred from an old phone to a new one.On Aug 7, 2017 7:21 PM, Grunthos <notifications@github.com> wrote:Please see our FAQ:
https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by dresdengirl** [comment]
I had over a 1000 books on mine (I'm a teacher). I am now uploading to Goodreads on my old phone and will go that route too. Thanks for getting back to me.

**Comment by Grunthos** [comment]
Please try an import, then go to 'Help'->'Send Information' and send the email to us.

Also, send us the CSV file you are trying to import.

**Comment by MelissaKline** [comment]
I've already done this.  After numerous e-mails back and forth with the creator of the app, I still wasn't able to get all of my books moved over.

**Comment by MelissaKline** [comment]
After months of trying to get the books to transfer over, that's what I had to do.  I'm a teacher as well.  I'm not as crazy about Goodreads, but at least I don't have to start all over.  Goodreads seemed to "sort" my books for me.  I didn't like that, but I was able to make it work.  Hope that Goodreads works for you.

**Comment by alkubrawiyyah78** [comment]
How to upload data from app into bookcatalogue.com web?
