### ISSUE TITLE
Trying to add a new book by scanning opens my "Michaels" app?

### ISSUE THREAD

**Issue by Brellana** [eleybourn/Book-Catalogue#778]
Short of uninstalling Michaels app what can be done? I have 2 scanning apps on device already.
And it isn't opening to any scanning feature in Michaels app either.

**Comment by Grunthos** [comment]
See our FAQ for scanning problems:

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)
