### ISSUE TITLE
merging databases

### ISSUE THREAD

**Issue by krominet** [eleybourn/Book-Catalogue#780]
Hello,
i created 3 BookCatalogue(s) with 3 different devices to go faster ...
but with sequential IDs i can't  merge.

The only issue is to export databases to another software (as tellico; or PMB for example); lost locals covers, merging databases, and re-link covers one by one ...  eventually import the result into BookCatalogue

a little silly: Not ?

An Idea ?

**Comment by Grunthos** [comment]
Backup to archive, and import each on the 'main' device. It should work. We will by preference use the UUID field which is very likely to be unique across the 3 instances.

**Comment by krominet** [comment]
thx ;-) good idea !
