### ISSUE TITLE
wrong charset code?

### ISSUE THREAD

**Issue by LosTresViajeros** [eleybourn/Book-Catalogue#784]
Hello from Europe,
I have a problem when importing the booklooker csv-file into my MS Excel: Some characters do not properly convert to correct characters, even if I have entered the text manually by myself correctly into the app (not taken from a database / web). Here is an example (it's Portugese, my main / work language is German):

"Maktub nÃ£o Ã© um livro de conselhos, mas uma troca de experiÃªncias. A maior parte dos textos se refere a ensinamentos que Paulo Coelho recebeu de seu mestre ao longo de 11 anos. Outros sÃ£o relatos de amigos ou pessoas desconhecidas que de uma forma ou de outra lhe deixaram uma mensagem inesquecÃ­vel. Finalmente, existem trechos de livros que ele leu e de histÃ³rias que pertencem Ã  heranÃ§a espiritual da raÃ§a humana. <br /><br />A proposta do autor Ã© reunir um apanhado da sabedoria universal destacando um ponto comum a todas as histÃ³rias: a busca da felicidade. Embora o desejo de ser feliz seja relatado em contextos tÃ£o diversos, fica fÃ¡cil concluir que, nÃ£o importa o lugar ou a Ã©poca, ele sempre se baseia nos mesmos pilares: amor, humildade, solidariedade e renÃºncia. <br /><br />Maktub oferece aos leitores uma oportunidade de refletir e se reencontrar. <br /><br />Se vocÃª estÃ¡ percorrendo o caminho de seus sonhos, comprometa-se com ele. NÃ£o deixe a porta de saÃ­da aberta atravÃ©s da desculpa: â€œAinda nÃ£o Ã© bem isto que eu queria.â€ Assuma o seu caminho. Mesmo que precise dar passos incertos, mesmo que saiba que pode fazer melhor o que estÃ¡ fazendo. Se vocÃª aceitar suas possibilidades no presente, com toda certeza vai se sair melhor no futuro."

Converting all the wrong characters (also like Ä ä Ö ö ß Ü ü in German) manually or even with the help of a replace-function is extremely time consuming. How can I fix this?

Thx M.

**Comment by Grunthos** [comment]
I may have misunderstood the question, but it sounds like a compatibility problem between booklooker and Excel, so I am not sure why this is a Book Catalogue question. Can you explain the connection to Book Catalogue?

**Comment by LosTresViajeros** [comment]
Interesting answer; I will give it one more try with an example:
I enter a book manually into the app. In one of the fields I enter text like "Ächtung der Großstadt mit Übung für Cafés..." (non-sense text in German, but has a lot of special characters like Ä ß Ü é just to explain...).
It looks perfectl when I view it in the app, e.g. in the booklist. (No excel involved so far, right?)
Then I export everything via csv.file.
Then I have a look at it with my txt editor - just to have a look at it (No excel yet, you name it.)
The file contains weird characters like in the example of the previous post. Obviously when I import the data afterwards, the wrong charset-characters are imported, too. I understand that it has something to do with stuff like utf-8, windows1252, iso8859-x etc., but I'm too much of a layman to fix this by myself. 
--
Solution? User / handling error by myself? Manual edit is not a solution...

**Comment by Grunthos** [comment]
Please email us the csv file in question via help-> send information 

On 11 November 2017 7:40:39 pm LHDT, LosTresViajeros <notifications@github.com> wrote:
>Interesting answer; I will give it one more try with an example:
>I enter a book manually into the app. In one of the fields I enter text
>like "Ächtung der Großstadt mit Übung für Cafés..." (non-sense text in
>German, but has a lot of special characters like Ä ß Ü é just to
>explain...).
>It looks perfectl when I view it in the app, e.g. in the booklist. (No
>excel involved so far, right?)
>Then I export everything via csv.file.
>Then I have a look at it with my txt editor - just to have a look at it
>(No excel yet, you name it.)
>The file contains weird characters like in the example of the previous
>post. Obviously when I import the data afterwards, the wrong
>charset-characters are imported, too. I understand that it has
>something to do with stuff like utf-8, windows1252, iso8859-x etc., but
>I'm too much of a layman to fix this by myself. 
>--
>Solution? User / handling error by myself? Manual edit is not a
>solution...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eleybourn/Book-Catalogue/issues/784#issuecomment-343649879

-- 
Sent from my Android device with K-9 Mail. Please excuse my dreadful spell-checker and my brevity.

**Comment by Grunthos** [comment]
Book catalogue exports in UTF-8. When you import into whatever you use (text
editor, excel, libreoffice) it *should* choose UTF-8 as the format. If it does
not, then the characters will be wrong.

The export file you sent looked find to my anglo eyes.

If this is still a problem then I suggest:

- add the book in Book Catalogue
- export it to CSV
- send me the file
- tell me which one it is (author, title, ID and/or row number in CSV file)
- tell me what it should look like and what it looks like in your app-of-choice
(probably a text editor is not the best option unless it understands UTF8)

**Comment by LosTresViajeros** [comment]
Thanks for the reply. Will give it a try again.

Another issue turned up: while editing a newly scanned book the app doesn't remember changes in the fields when switching between the tabs "details" and "notes". 

Example: First I change /correct the title, set the Format to Hardcover" in "details". Then I switch to the "notes " tab, do some entries there. However,  when I switch back to "details" for some reason (forgot something or simply to check) the changes from before are gone. Can be quite tiring when scanning 50+ books... .

Thx M.


Gesendet mit TypeApp ​

**Comment by Grunthos** [comment]
The loss of data should be fixed in the next release.
