### ISSUE TITLE
How to clear credentials for Goodreads from the Android app?

### ISSUE THREAD

**Issue by howardtu2u** [eleybourn/Book-Catalogue#786]
Book Catalogue Version 5.2.1
1. When I try to synchronize with Goodreads I receive the attached pop-up screen
![screenshot_20171211-112315](https://user-images.githubusercontent.com/34456854/33849686-31d7e506-de66-11e7-8045-b5782153bb88.png)
2. The error log is attached
[error.log](https://github.com/eleybourn/Book-Catalogue/files/1549116/error.log)
3. I removed the authorization from Goodreads so it could be set up again, but cannot find how to clear the Goodreads credentials so I can set up new credentials between the applications.
4. Uninstalling and reinstalling Book Catalogue did not solve the issue.
5. Any advice is greatly appreciated

**Comment by Grunthos** [comment]
Thanks for the bug report; this has been fixed in 5.2.2 which which has been released.

**Comment by howardtu2u** [comment]
Thanks for the quick work. I can synchronize with Goodreads now. If I can help QA bug fixes and/or help update/review documentation let me know. I was a QA engineer for many years.
