### ISSUE TITLE
Choose another barcode-scanner

### ISSUE THREAD

**Issue by natrius** [eleybourn/Book-Catalogue#790]
**Problem:**
Its for me right now not possible to scan with the barcode-scanner. I installed instead the "QR Scanner" that is working perfectly fine. Now, when i uninstall the "barcode-scanner" the book-catalogue does not ask me what app i would like to use, instead it just opens "untis" for whatever reason. 

**Possible solution:**
So, please make it possible to choose your own barcode scanner, or like https://github.com/brarcher/loyalty-card-locker with an direclty included barcode scanner.

**Android Version:**
7.1.2

**App Version:**
3.8.1 (through f-droid)
(I tried with 5.0.7 too, fyi, same problem)

If more information is needed, please tell me. 

Greets

**Comment by Grunthos** [comment]
On 25/01/2018 7:35 AM, Stefan wrote:
> So, please make it possible to choose your own barcode scanner, or like
> https://github.com/brarcher/loyalty-card-locker with an direclty included
> barcode scanner.

You can choose one of three options: Zxing-compatible; Zxing (exact app match);
and Pic2Shop (exact app match; has ads; good for low light and poor cameras).

We do not support any other scanners, and Zxing is free, has no adds, and works
well in general).

**Comment by natrius** [comment]
But none of this scanners is available through f-droid store, also the apps are not available to download directly as .apk. 
If there is no discussion about that or its technically not good, just close this issue.

**Comment by Grunthos** [comment]
I *think* the problem is that not all scanners return data in the same way, so we have to limit ourselves to a small set of scanners.
