### ISSUE TITLE
Update f-droid app

### ISSUE THREAD

**Issue by natrius** [eleybourn/Book-Catalogue#791]
Hello, 
please update the f-droid version. Right now its 3.8.1 while here its already 5.2.0 as far as i'm aware.
Greetings

**Comment by Grunthos** [comment]
We don't maintain the FDroid version; we do maintain the Google Playu version. FDroid (last time I looked) required pure open source, but a tiny part of our code includes private API keys to goodreads, amazon etc, so we can't release those source files.

**Comment by natrius** [comment]
There is a lot of help in the f-droid forum regarding that. But it would also be possible to create your own repo in f-droid:
https://f-droid.org/en/tutorials/create-repo/

Greetings

**Comment by davidchisnall** [comment]
F-Droid doesn't require that it's entirely open source (though it will flag it as containing non-free components if it isn't).  They do require that they be able to build the release themselves, (unless you want to provide your own repo).  This is, apparently, currently failing because the build fails if you don't embed an Amazon key, rather than simply continuing without the Amazon integration.

**Comment by Rudloff** [comment]
Hello, I am an F-Droid contributor.

To clarify, the Amazon API key is not the main reason we can't publish this app anymore. (Providing a fake Amazon key seems to simply disable Amazon search but the app still builds and works.)
The main issue is that the repository contains [several prebuilt JAR files](https://github.com/eleybourn/Book-Catalogue/tree/master/libs) and we require those to be either built from source or fetched from a trusted repository like jCenter or Maven Central.

> F-Droid doesn't require that it's entirely open source

We do require apps to be entirely FOSS.

**Comment by nemobis** [comment]
> The main issue is that the repository contains several prebuilt JAR files and we require those to be either built from source or fetched from a trusted repository like jCenter or Maven Central.

So it would be enough to change the build file to add an option to do so?

**Comment by Rudloff** [comment]
Yes, I guess a build flag or a [build variant](https://developer.android.com/studio/build/build-variants) would be OK.

**Comment by jkirk** [comment]
It would be awesome to have this App in F-Droid. @Grunthos Do you think this issue could at least can get re-opened?

**Comment by SnorrenEnzo** [comment]
I would love to be able to use a recent version of this app from F-droid! It would allow people to disconnect even more parts of their phone from the Google services.
