### ISSUE TITLE
Update cover "from camera" forces a square image

### ISSUE THREAD

**Issue by White-Owl** [eleybourn/Book-Catalogue#792]
I added a book, for which no one provided cover yet (yeah that happens :) )
I tried to replace the cover "from camera". The camera turned on, I managed to make a good portrait-style photo (height>width) of the cover, but then the square box appears and I am forced to replace the cover thumbnail with a square image, cutting off top and bottom of the original image.

**Comment by Grunthos** [comment]
You can drag the square edges to make a rectangle. It's for cropping the image.
