### ISSUE TITLE
Unable to export database

### ISSUE THREAD

**Issue by macmcd47** [eleybourn/Book-Catalogue#798]
I have been running Book Catalogue on a Sony Xperia Z5 for some time but was unable to backup to SD card. I have now changed my phone to a Samsung S8 and want to transfer the database to the new phone but am struggling. If I select Admin\Backup to Archive on the Z5, it opens in /storage/sdcard0/bookCatalogue. If I select Save\All Books I get the error message saying 'Backup Failed'. If I try again but this time instead of the default path I select the 'Parent' button twice, the path changes to '/' but there are no selectable locations below.

If I carry out the same procedure on the S8 the default path is /sdcard/bookCatalogue and I am able to backup the database successfully. If I select the Parent button twice I am able to select the sdcard in the window below. Therefore it looks like Book Catalogue on the Z5 can't access the SD card while plenty of other apps are able to. I have used the same SD card in both phones and have tried two others with a similar lack of success. The Storage permission is enabled on both phones for Book Catalogue.

I have tried to copy the whole Book Catalogue directory over to the S8 but it just starts as a blank database. I'm sure I'm missing something very simple here and I apologise for the length of the post but would appreciate some help as I have over 1,000 books in my database.

Many thanks,
Mac.

**Comment by macmcd47** [comment]
Is anyone able to help with this as it is proving somewhat frustrating.

Thanks,
Mac.

**Comment by eleybourn** [comment]
Apologies for the radio silence.

Are you getting the same error if you try both export and backup?

**Comment by macmcd47** [comment]
Sorry for the delay in getting back to you but I manged to export to csv. I imported that into the S8 and then rebuilt the covers from the internet. For some reason Book Catalogue on the Z5 could not see the SD card which is the same one as I am using in the S8. I seem to have my database back now though.


Thanks,
Mac.

**Comment by ericzolf** [comment]
I have exactly the same issue on a BQ Aquaris X Pro with Android 8.1 - I guess that's it's an issue with access right to storage which appeared at some point in time in Android (Backup used to work on Android 5.1). Export isn't impacted because it's sharing the CSV file, not trying to save it explicitly to the file system. A solution would be good.

**Comment by cathriene101** [comment]
The old app deleted itself on my phone when Google Play removed it and/or you removed it from my phone. I tried to download the beta version to access any files that might be left, but it isn't finding any. Help!

**Comment by Grunthos** [comment]
Is this still an issue?

There is a new beta version available for download here; if you wish to test, please backup your catalogue first:

https://drive.google.com/open?id=1EYyTvjHeFEr3c-FzdD6-oEnRHMUZEuwk

Let me know if you have any news (good or bad).

**Comment by Grunthos** [comment]
Updated beta version at:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by ericzolf** [comment]
Would it be possible to have beta version in Google Play? There used to be such a feature to offer beta versions to selected persons. I haven't done back-ups for ages and it's making me nervous indeed...

**Comment by Grunthos** [comment]
Its rolling out on Google Play now, but because they removed the app due to our donation links, we have had to jump through a few hoops to get it back.

**Comment by Grunthos** [comment]
Have a look at the FAQ for useful info on moving to a new phone.

**Comment by Grunthos** [comment]
Latest betas will be in this folder:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by Grunthos** [comment]
Version 6 had a complete remodeling of backups an it should address this issue
