### ISSUE TITLE
Original title

### ISSUE THREAD

**Issue by Acki01** [eleybourn/Book-Catalogue#799]
Is there a way to add the original title of a translated book?

**Comment by liquidpredator** [comment]
This feature will be good for me too. Thanks.

**Comment by White-Owl** [comment]
I am against it.

The only case when you can make use of the original title is when you can actually read that language. But if can - you will always know what the original title is just by looking at the translated one. Keeping an original title as a special field begs for an ability to sort and search by it. And in an actual multi-language library it can be confusing: Are you looking at the translation or not? And if you have same book in several different languages - the confusion will just build up.
So I would prefer to have book registration only in the language the book is printed in.

And anyway, you can always add anything you like into 'comments' field.

**Comment by Youtch** [comment]
>  add anything you like into 'comments' field.
I will opt for this resolution !
