### ISSUE TITLE
eBooks

### ISSUE THREAD

**Issue by Neofit26** [eleybourn/Book-Catalogue#802]
Hi,

I am glad I have found this app. About half my books are in Russian and Book-Catalogue is the only app that can look up those ISBNs. So, 371 scans and an exhausting day later, all my paper books are catalogued. Which still leaves me with a few dozen ebooks. These past years I've been almost exclusively reading books from Amazon and litres.ru on my Kindle. Is there a trick to quickly scan those? I didn't find anything in the app, and the only thing I can think of is manually entering all the ISBNs, which sounds even more exhausting than scanning and reorganizing all those paper books. :)

PS: I'm not sure this qualifies as an issue. Is there a forum to discuss Book Catalogue features, tricks and stuff?

**Comment by Grunthos** [comment]
It's not possible. I have made many requests from Amazon to open up the Kindle app to return a list of owned books (or similar), but received no response. I manually add all my ebooks via ISBN. It's a pain.
