### ISSUE TITLE
Synchronization with GoodReads doesn't work?

### ISSUE THREAD

**Issue by Neofit26** [eleybourn/Book-Catalogue#803]
Hi,

I have scanned 375 books into BC. I sent them to GR, a lot of them made it through, but 100+ did not, all of them foreign books that apparently GR cannot find the ISBN for. This is not the issue, I am having problems synchronizing the other way.

I had 239 books in GR after that import. I added 17 Kindle books for a total of 256. I then try the "Synchronize with GR" and "Import everything from GR" commands. The background tasks seem to end successfully, but no books are added to BC, I still have 375 books in BC. 

Is this normal?

**Comment by Neofit26** [comment]
I  think I have figured it out. When entering an ebook in GR through the ASIN we see on Amazon, they do not look up the corresponding ISBN (because come on, who needs a non-Amazon ID on Planet Amazon in the Amazon galaxy?). Then when they generate their export file they do not export the ASIN field, so we end up with books that have no ASIN nor ISBN, and BC won't show them by default. 

As a comparison, when I add the same book to BC through an ASIN number, BC does it due diligence and looks up the corresponding ISBN, and gives us an export file with the proper ISBN.

Now when synchronizing BC with GR, do they present an ASIN field that BC could use to look up the ISBN as when it does when I manually add a book through the ASIN?

**Comment by Grunthos** [comment]
This is a thorny issue. One possibility would be to get the ASIN from GR (if possible), then get the ISBN from our end etc. Can you give a couple of books with this problem, so I can experiment?

**Comment by Grunthos** [comment]
Goodreads have disabled all public API access so we can no longer sync with them
