### ISSUE TITLE
Book catalogue no more present on Playstore ?

### ISSUE THREAD

**Issue by Villard** [eleybourn/Book-Catalogue#814]
hello
the book catalogue seems to be no more present on the playstore. 

I can't find it either via my Android palystore or via a PC. 
I thought first it was because I'd upgraded my Galaxy to Android Pie. After the upgrade, I got a notification that Book catalogue has not been validated for Android Pie. But even on searching it in the Playstore via my PC internet browser, I can't find it. 

I'am annoyed ! Il love this app and I woud be desperate if I need to reinstall it and can't find it. 
thanks for ypour reply 
Villard

**Comment by eleybourn** [comment]
It's coming back. Google took it off the play store and we are quickly
making the needed changes before uploading it again.

**Comment by Villard** [comment]
Thanks a lot for this very positive answer ! Long life to Book catalogue !

**Comment by Grunthos** [comment]
Hi,

Sorry for the inconvenience; please bear with us. Google have taken it upon 
themselves to de-register the app because we solicit donations. We are making 
changes to remove the donations links, but it will take time because there are 
other changes that are now required by Google.

If you like, I can send you an APK file for manual install.

Otherwise, the app should be back in the next month.

Thanks!

**Comment by Villard** [comment]
Hello
It's OK for the time being as far as I do not change or reset my phone.
I was just annoyed not to see anymore my favorite Android application (Really true !) and I wanted to get good news 
Good job, thanks

**Comment by rickibarnes** [comment]
Oh thank goodness! Just got a new phone and devo to find I couldn't download it.

**Comment by Grunthos** [comment]
A beta APK with minor functionality additions can be found here:

https://drive.google.com/open?id=1j7uomwyYR29NhJ8md0XQb2VnHEFOJqc6

**Comment by davidchisnall** [comment]
Any chance of an updated F-Droid build?

**Comment by cathriene101** [comment]
Hi! I'm trying to access my data from my previous version of this app. The beta version isn't opening it. The old version deleted itself!! And I had REALLY hoped getting the beta version would allow me to access the info. Why isn't it working?

**Comment by krystal16** [comment]
> Hi! I'm trying to access my data from my previous version of this app. The beta version isn't opening it. The old version deleted itself!! And I had REALLY hoped getting the beta version would allow me to access the info. Why isn't it working?

I can only guess this is a known issue that is hopefully being worked on.  I can't import my library that I backed up from an old phone, either.  I've posted a request and it seems that the developer is busy fixing things as I've had no response either.

**Comment by ctjayhawker** [comment]
Hi! 
Book catalogue seems still not to be present in the play store, and now it seems that the only databases it accesses in order to find information are Goodreads and library thing. What happened to Amazon and Google books?

**Comment by ctjayhawker** [comment]
Addendum. Never mind about part of that, it seems that it does still check Google. It just comes and goes so fast it's hard to see. But Amazon is a huge loss if we're no longer able to access that for information.

**Comment by fmartelg** [comment]
This is (was?) a great app. Two months have gone by. Still no app on Google Play. 

Grateful for sense of timeline before I switch to another app. 

Than you.

**Comment by Villard** [comment]
I come back to get some news. Bookcatalogue is so a great app,
Cheers

**Comment by tapivoka** [comment]
Me too , I was surprised when have not found the app on play store... I recommended the app to my friends and now they have to install another app with less functionality... Please come back on Google play!

**Comment by Happeesupermom** [comment]
I'm disappointed & frustrated not to see a app in Google Play any longer. I see your comments above that it will come back, but so much time has passed that I'm getting worried again. Please tell us if you have an estimated date? Thank you! Love this app and would really hate to use another.

**Comment by Grunthos** [comment]
The changes required for mandatory API level updates are done. Complying with Google's demands to remove all donation links and requests is in progress. 

This is more fraught because we want to be absolutely sure all are gone since we are totally at the mercy of Google here, but we also want to leave aspects of the code in place for services line fdroid etc. 

On 21 June 2019 12:04:01 pm AEST, Happeesupermom <notifications@github.com> wrote:
>I'm disappointed & frustrated not to see a app in Google Play any
>longer. I see your comments above that it will come back, but so much
>time has passed that I'm getting worried again. Please tell us if you
>have an estimated date? Thank you! Love this app and would really hate
>to use another. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eleybourn/Book-Catalogue/issues/814#issuecomment-504261026

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Grunthos** [comment]
...as well as keep the potential to advertise a Pro version or donations via google play, if we ever want to

On 21 June 2019 12:04:01 pm AEST, Happeesupermom <notifications@github.com> wrote:
>I'm disappointed & frustrated not to see a app in Google Play any
>longer. I see your comments above that it will come back, but so much
>time has passed that I'm getting worried again. Please tell us if you
>have an estimated date? Thank you! Love this app and would really hate
>to use another. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eleybourn/Book-Catalogue/issues/814#issuecomment-504261026

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rodrigomanhaes** [comment]
Can you provide some apk meanwhile?

**Comment by Grunthos** [comment]
On 24/06/2019 3:41 am, Rodrigo Manhães wrote:
>
> Can you provide some apk meanwhile?
>

Temporary APK is here:

https://drive.google.com/open?id=1j7uomwyYR29NhJ8md0XQb2VnHEFOJqc6

**Comment by Villard** [comment]
Hello
Very good news ! I thank you to share them to all of us. All my support to you. I al looking forward to the update for ly best loved Android application.
Martin

**Comment by ctjayhawker** [comment]
anything new? I'm using it right now and unless it is just coming and going too fast for the eye to see, it is still not referencing Amazon in a search, which is huge. Not to mention that we're still unable to update.
Thanks!

**Comment by davidshrader** [comment]
I love this app a lot! However, it no longer accesses Amazon. I get failures every time I attempt to add a book even using the ASIN! Isn't that Amazon's unique number?
Thanks,
David

**Comment by ctjayhawker** [comment]
UUUUUUUPDAAAAAATE!!! :-\

**Comment by Grunthos** [comment]
The update is now being tested. If you would like to help test, send us an email.

**Comment by Grunthos** [comment]
Updated beta APK location and details (new version):

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by Hardcover214** [comment]
Testing the new update now! Book Catalogue is my most used Android App, so this is very good news!!!

At first glance, cover previews have different sizes. In previous versions, all image previews were the same size, regardless of the image source.

**Comment by Villard** [comment]
Hello
Thank you for this update ! I was relieved when PlayStore informed me for it.
Very good job. Seems fine
