### ISSUE TITLE
Problem Synchronizing with Goodreads

### ISSUE THREAD

**Issue by howardtu2u** [eleybourn/Book-Catalogue#815]
Starting about 2 months ago the synchronization with Goodreads fails on the send part.
It appears that download works and there are no events in the log. I am using version 5.2.2.

**Comment by howardtu2u** [comment]
Is this a known issue?
Is there an ETA for when the application will be back in the Google Play store?

**Comment by Grunthos** [comment]
Can you try to sync, wait a while, then go to "Help"->"Send Logs".

Also, can you look in "Admin & Prefs"->"Background Tasks" and let me know what you see there.

Finally, have you tried de-registering and re-registering on goodreads?

**Comment by Grunthos** [comment]
See Issue 814 for comments on availability in Store

**Comment by howardtu2u** [comment]
Thanks for the reply.
I sent the log files and copied them here as well.
There are no events logged in Background tasks, a screen shot is attached.
I have not de-registered and re-registered on goodreads yet. If there is a known issue with Goodreads connections I did not want to lose any debug data. If I do this step are there any relevant log files that can help debug the issue?
Thanks for your help
[error.log](https://github.com/eleybourn/Book-Catalogue/files/3060781/error.log)
![Screenshot_20190409-125704_Book Catalogue](https://user-images.githubusercontent.com/34456854/55831748-b6e60e00-5ac8-11e9-8452-65b1187612a3.jpg)

**Comment by howardtu2u** [comment]
DB File attached
[bookCataloguebookCatalogueDbExport-tmp.zip](https://github.com/eleybourn/Book-Catalogue/files/3060785/bookCataloguebookCatalogueDbExport-tmp.zip)

**Comment by Grunthos** [comment]
Can you click on the item in "Background Tasks", and send or post the details? It should have a little more info.

**Comment by howardtu2u** [comment]
Hi, 
The screen shot above shows everything that is shown when I look at background tasks. Is there something that can be blocking the additional information you are looking for to be collected?

**Comment by Grunthos** [comment]
Yes, click on the item in that list. It may should a list of other errors.

On 10 April 2019 10:02:34 am AEST, howardtu2u <notifications@github.com> wrote:
>Hi, 
>The screen shot above shows everything that is shown when I look at
>background tasks. Is there something that can be blocking the
>additional information you are looking for to be collected?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eleybourn/Book-Catalogue/issues/815#issuecomment-481483612

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by howardtu2u** [comment]
Sorry there is just one entry and it shows 0 errors. I started the task again, it has 8 more attempts. When I tried to run the task again, it is blocked because the previous one did not complete. When it completes I'll try to run again and see if there are any errors recorded. 
The error.log file has some entries in it, are they helpful


An Exception Occured @ 2019-04-09 13:02:18
In Phone SM-N950U (28) 
At line 40, column 1158: not well-formed (invalid token)
org.apache.harmony.xml.ExpatParser$ParseException: At line 40, column 1158: not well-formed (invalid token)
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:519)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:478)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:187)
	at com.eleybourn.bookcatalogue.goodreads.GoodreadsManager.parseResponse(GoodreadsManager.java:473)
	at com.eleybourn.bookcatalogue.goodreads.GoodreadsManager.execute(GoodreadsManager.java:386)
	at com.eleybourn.bookcatalogue.goodreads.api.ShowBookApiHandler.sendRequest(ShowBookApiHandler.java:158)
	at com.eleybourn.bookcatalogue.goodreads.api.ShowBookByIdApiHandler.get(ShowBookByIdApiHandler.java:72)
	at com.eleybourn.bookcatalogue.goodreads.GoodreadsManager.getBookById(GoodreadsManager.java:877)
	at com.eleybourn.bookcatalogue.goodreads.GoodreadsManager.sendOneBook(GoodreadsManager.java:668)
	at com.eleybourn.bookcatalogue.goodreads.SendAllBooksTask.sendAllBooks(SendAllBooksTask.java:136)
	at com.eleybourn.bookcatalogue.goodreads.SendAllBooksTask.run(SendAllBooksTask.java:79)
	at net.philipwarner.taskqueue.QueueManager.runOneTask(QueueManager.java:350)
	at net.philipwarner.taskqueue.Queue.handleTask(Queue.java:168)
	at net.philipwarner.taskqueue.Queue.run(Queue.java:127)

**Comment by Grunthos** [comment]
Best guess based on those errors would be for you to de-register the app on 
goodreads then re-enable it. That would be the next step anyway.

**Comment by howardtu2u** [comment]
Thanks,

I tried the following steps.
Revoked access on Goodreads
Forget credentials on Book Catalogue, observed the Forget Credentials button was gone
Closed Book Catalogue
Authorize access on Book Catalogue
Refresh page on Goodreads and see the application
[error.log](https://github.com/eleybourn/Book-Catalogue/files/3061526/error.log)
 has access again
Cleared the Background task so I could try to sync again
Started the sync task - seems to be failing like before
A new error log is attached.
I noticed some files in the main directory with names like tmp_GB.jpg_3886193225 and tmp_LT_LARGE_0553560735.jpg. They all seem like book covers. Is it expected that there should be some temp files like this?

**Comment by howardtu2u** [comment]
If you update the app and get it back in the Google Play Store I'll update then and see if the synchronizations work then

**Comment by Grunthos** [comment]
There is a new beta version available for download here; if you wish to test, please backup your catalogue first:

https://drive.google.com/open?id=1EYyTvjHeFEr3c-FzdD6-oEnRHMUZEuwk

I also think that goodreads have fixed some problems at their end. Let me know if you have any news (good or bad).

**Comment by howardtu2u** [comment]
Hi,

I have only installed applications from the Google play store. What do I need to do to install the beta version on my android phone?

Thanks,
Howard
________________________________

**Comment by Grunthos** [comment]
Hi Howard,

Thanks for the quick response.

The steps to install an APK manually vary for each phone, but the basic steps are:

- download the file

- use whatever file manager came with your phone to locate the APK file 
(probably in the Downloads directory, but may be elsewhere

- open the APK (usually just click on it in file manager)

You will then get a warning about installing apps that did not come from the 
play store and will need to go to settings to allow this; some phone have the 
ability to say "Allow Once", others you need to remember to un-set this after 
the install.

Once you have allowed non-store installations, install the APK and follow the 
instructions. And don't forget to disable "non market" installations afterwards.

Alternatively, if this is too much of a pain, we are trying to get the beta 
version reinstated on the market, so you could just wait, but I have no idea how 
long this process will take.

Thanks again!

**Comment by howardtu2u** [comment]
Hi,

I have an android phone, Samsung Note 9. I'd like to help if I can, so I'll see if there is an option that lets me install a .apk file not from the store.
If it's successful, I'll let you know.

Would the test I can do be to synchronize with Goodreads?

Best,
Howard

________________________________

**Comment by howardtu2u** [comment]
Hi,

I installed the beta version, it appears to work the same as before. I did not reboot the phone but I checked the version and saw it was the beta version.
Attached is the error log.
One suggestion for enhancements to the error log, you may want to capture the version of book catalogue and the OS version.

I allowed the installation even though it was not from the app store, do you know how I can disable that in case the Android SW has a hole and lets other apps that are not from the app store get installed?

Let me know if there is any other useful information I =can send you.

Best,
Howard


________________________________

**Comment by howardtu2u** [comment]
One more issue.

Replace Thumbnail does not work.
To Reproduce

  1.  Verify there is a valid ISBN number
  2.  Select Replace Thumbnail
  3.  Observe that the application screen look like has a dark shade over it.
  4.  I can back out of the entry and use the application so it is not hung.


________________________________

**Comment by Grunthos** [comment]
Hi,

Thanks for testing, it's much appreciated. To answer your questions:

1. Best test is to use it as much as possible; we have had to make very 
substantial under-the-hood changes to update the app; every activity has been 
affected. But to answer your specific question: yes, goodreads should be checked 
if you normally use it.

2. To disable non-store installs, there should be a relevant entry in settings. 
In my phone it's called "Install apps from external sources".

3. I can not reproduce the "replace thumbnail" problem. Can you try to do it, 
then go to "Help"->"Send Information" and send us the resulting email? For me, 
when I select "Replace Thumbnail" there is a subment that has "From Camera", 
"From Gallery" and "From Other editions". Do you see this?

Thanks again!

**Comment by Grunthos** [comment]
Updated beta version location at:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

This addresses some issues with cropping and cover images.

**Comment by Grunthos** [comment]
Updated beta version at:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by Grunthos** [comment]
Thumbnail replacement fixed in development code; will be in next beta.

Can you test goodreads with most recent beta and let me know if it now works. If it doesnt, go to "Help"->"Send Information".

**Comment by howardtu2u** [comment]
OK,
Please send me the .apk file.

/ht
________________________________

**Comment by Grunthos** [comment]
The APK can be downloaded from:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by howardtu2u** [comment]
I successfully replaced the thumbnail with the beta build.

Best,
Howard
________________________________
