### ISSUE TITLE
No export file found

### ISSUE THREAD

**Issue by krystal16** [eleybourn/Book-Catalogue#817]
I think I posted this originally in the wrong place.  Sorry.

I exported my books to a .csv on my old phone, emailed it to myself, then just imported into a new phone.  I get the error No export files found.  I exported one book from the new phone to itself and it is in the same file folder that I have my saved one in, but it is seeing neither of them.  I have taken  a screen shot below of the files and where they are in the Book Catalogue folder on my Moto G6 Play.
![57004908_1287695301398769_2003259359164891136_n](https://user-images.githubusercontent.com/49622686/56099268-9f4bc280-5ed8-11e9-86ea-d468735911db.png)

**Comment by Grunthos** [comment]
Can you show use the name and contents of the folder in which you placed the export CSV files?

**Comment by Grunthos** [comment]
Several issues with exports and backups have been fixed in version 6
