### ISSUE TITLE
Authorising Goodreads with Huwaei

### ISSUE THREAD

**Issue by MattAust1** [eleybourn/Book-Catalogue#819]
Wondering if anyone has problems authorising Goodreads through Book-Catalogue on a Huwaei phone.  It's always work on my previous Samsung phones but now I hit authorise and the progress animation spins for a few seconds then nothing happens.  Suspect this is a phone setup issue but can't find the fix.

**Comment by Grunthos** [comment]
There is a larger issue with Goodreads in general that is still being investigated.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MattAust1** [comment]
Great, thank you.

**Comment by Grunthos** [comment]
Is this still happening for you? I *think* the goodreads issue is resolved.
