### ISSUE TITLE
Can't authorize Goodreads on new Samsung Note 10

### ISSUE THREAD

**Issue by VariableReferee** [eleybourn/Book-Catalogue#836]
I've been using Book Catalog for years and I love it. I just upgraded to a new Samsung Note 10 and I am unable to authorize access to Goodreads-- I just get a brief spinning icon that appears and disappears. I have followed the FAQ but nothing seems to work. I tried setting Chrome as the default, then Firefox as the default, but every time I click authorize access it just spins and then the spinning icon disappears and nothing happens. I tried removing the app and reinstalling the app and that didn't work. I am able to import the backup from my old phone so all my books are there, but I really only use this app to synchronize with Goodreads. Please help!

**Comment by VariableReferee** [comment]
More info:  I was able to remove access and re-authorize access on my old phone without a problem, so I know it's not the Bookreads site. I think it has to do with something in the way that the Book Catalog app is trying to open the browser. What can be done?

**Comment by VariableReferee** [comment]
FIXED!

I was able to fix this problem by uninstalling the app (version 5.1.2) and reinstalling the most recent version 5.2.2 here: https://apkpure.com/book-catalogue/com.eleybourn.bookcatalogue

I originally downloaded the app from Amazon, but that version is 5.1.2. This really has to be fixed! The app is no longer on Playstore and the first hit you get when looking for it leads you to Amazon. So anyone trying to download the app is going to get an old version.

**Comment by Grunthos** [comment]
Hi,

That's useful information; can you try to authorize on the phone that doesnt 
work, then wait a few seconds and go to "help"->"Send Information"?

Thanks!

**Comment by VariableReferee** [comment]
You mean uninstall the working version (5.2.2), reinstall the problematic version (5.1.2), try to reauthorize, then send the info?

**Comment by Grunthos** [comment]
Ah, sorry. It didn't register that you had it working with the latest version. If so, just keep the working one!

On 26 September 2019 11:46:04 pm AEST, VariableReferee <notifications@github.com> wrote:
>You mean uninstall the working version (5.2.2), reinstall the
>problematic version (5.1.2), try to reauthorize, then send the info?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eleybourn/Book-Catalogue/issues/836#issuecomment-535509034

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Grunthos** [comment]
There is a new beta version available for download here; if you wish to test, please backup your catalogue first:

https://drive.google.com/open?id=1EYyTvjHeFEr3c-FzdD6-oEnRHMUZEuwk

**Comment by Grunthos** [comment]
Updated beta location at:

https://drive.google.com/open?id=1jT80Jfi8CPolzPc8j00o1QSqghD2mg-R

**Comment by VariableReferee** [comment]
What is the difference between version 5.2.2 and 5.2.3? I don't want to test a beta without knowing what changed.   :-)

**Comment by VariableReferee** [comment]
Did version 5.2.4 get officially released? It looks that way when I see it on github, but I don't know how to get the new version.

.

**Comment by eleybourn** [comment]
Are you using the latest version from the play store? 
https://play.google.com/store/apps/details?id=com.eleybourn.bookcatalogue

**Comment by VariableReferee** [comment]
LOL I thought it wasn't available on Playstore for some reason. I'm an 
idiot.  LOL  I just updated it and now I'm running 5.3.0-3-distplay. 
Sorry for the false alarm.

------ Original Message ------
