### ISSUE TITLE
Can transfer the data or upload to bookcatalogue.com?

### ISSUE THREAD

**Issue by alkubrawiyyah78** [eleybourn/Book-Catalogue#846]
Is it the web bookcatalogue.com same like LibraryThing that we can transfer and upload the data from app? If can, how i can upload it into web?

**Comment by Grunthos** [comment]
We do have book-catalogue.com and that will/may one day support backup/upload.

However the next release (in beta) will allow backups to go to or come from other places (eg. drive)
