### ISSUE TITLE
Link to wiki broken

### ISSUE THREAD

**Issue by tomjuggler** [eleybourn/Book-Catalogue#847]
Hi, when you go to the main GitHub page the link to http://wiki.github.com/eleybourn/Book-Catalogue/ is broken. Maybe remove this link, or fix? 

Otherwise, awesome app, thanks! I'm busy cataloguing my entire home library, because why not? Also, this is going to be great for keeping track of library books, when they finally let us out (Coronavirus Lockdown Blues)

**Comment by jarrodjackson** [comment]
Correct URL is https://github.com/eleybourn/Book-Catalogue/wiki

**Comment by eleybourn** [comment]
Thanks for that. I've fixed it.
