### ISSUE TITLE
Can' create a backup of my library

### ISSUE THREAD

**Issue by losvedese** [eleybourn/Book-Catalogue#849]
Hello,
I'm running book catalogue on a Samsung Galaxy A71 with Android 10 and I can't create a backup file. When I tap on create backup, the app shows me the path storage/sdcard1, since I do not have an sd card I change it to storage by tapping on the "go back" arrow, then I tap on save button but the procedure fails and a popup message appears saying that it is not possible to save on sd card.
How do I fix this?

**Comment by losvedese** [comment]
![Screenshot_20200710-124836_Book Catalogue](https://user-images.githubusercontent.com/68108501/87146804-c9db2580-c2ab-11ea-8ed9-c828a4d6c821.jpg)

**Comment by Grunthos** [comment]
This is fixed in the next release (currently in beta): We use standard android tools for location selection.
