### ISSUE TITLE
Goodreads sync does not sync the "Read date" when day is not set.

### ISSUE THREAD

**Issue by JeanFred** [eleybourn/Book-Catalogue#851]
Both BookCatalogue and GoodReads allow to file the “Date read” with precision to only the year, the year+month, or the full date. When the full date is not used, then this not properly synced with Goodreads.

Steps to reproduce:
* Add a book in BookCatalogue, with 'Read', 'read' shelf, and 'Read Date' with only the month precision, eg “July 2020” (but not “July 31st 2020”)
* Send to Goodreads (either with full sync or individual "Send to Goodreads”)

Expected:
* Book is added to Goodreads as read, with the "Date read" field in Goodreads is set to “July 2020”)

Result: 
* Book is added to Goodreads, but "Date read" field is not set.

(I’m under the impression this used to work, so it might be an API change on Goodreads side?)

--- 
Version: latest 5.3.0.4 from PlayStore

**Comment by JeanFred** [comment]
I tried hunting down where in the code this is happening.

I assume the sync is done in [`sendOneBook`](https://github.com/eleybourn/Book-Catalogue/blob/90080be0b58c3d1ff572429b693cf60f1d48afa1/src/com/eleybourn/bookcatalogue/goodreads/GoodreadsManager.java#L650) ; I followed to [`updateReview`](https://github.com/eleybourn/Book-Catalogue/blob/90080be0b58c3d1ff572429b693cf60f1d48afa1/src/com/eleybourn/bookcatalogue/goodreads/GoodreadsManager.java#L627), which sends to [`ReviewUpdateHandler`](https://github.com/eleybourn/Book-Catalogue/blob/8b87c2dab13f9f8f96bd100e65009696e0fe2aab/src/com/eleybourn/bookcatalogue/goodreads/api/ReviewUpdateHandler.java#L85-L86), which sends to the [`review.edit`](https://www.goodreads.com/api/index#review.edit) API endpoint, with the end date is retrieved via [`getReadEnd`](https://github.com/eleybourn/Book-Catalogue/blob/8b87c2dab13f9f8f96bd100e65009696e0fe2aab/src/com/eleybourn/bookcatalogue/BooksRowView.java#L146)

The documentation of the endpoint is:
> review[read_at]: Date (YYYY-MM-DD format, e.g. 2008-02-01) (optional)

So, while the GoodReads UI does support month-only precision, it might be that the API does not?

**Comment by Grunthos** [comment]
Goodreads API is now dead and buried courtesy of Amazon/goodreads.
