### ISSUE TITLE
Covers not backed up?

### ISSUE THREAD

**Issue by ctjayhawker** [eleybourn/Book-Catalogue#866]
I recently got a new phone, so prior to firing it up, I backed up my Catalogue info to my PC, and imported it today. However, some covers evidently didn't make the trip. It SEEMS that these are the covers I had to create myself, the internet not having them available for download. Are those not backed up?

**Comment by Grunthos** [comment]
See our FAQ for moving to a new phone:

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)

Covers are backed up to an archive file.
