### ISSUE TITLE
Problem accessing SD-card

### ISSUE THREAD

**Issue by nypra1314** [eleybourn/Book-Catalogue#870]
Yesterday I received another update from Android. On my Nokia I have Android 11.
Untill yesterday I had no problems whatsoever with BookCatalogue over the many years I use it.
But suddenly I have no books in my Bookmanager. Of course I have Backups on my SD-Card and on My Drive. Luckily I made them yesterday.
BookCatalogue looked like I just installed new it this morning... So like I did before I tried to import my backup file but this time it didn't work. I got the message: Import failed. Check if your SD-Card is accessible.... It looks exactly like this post: 
Issue 849: Can't create backup of my library.

I uninstalled BM and installed it again, restarted my phone. No luck. 
I tried to make a new backup file(no books inside) That worked! This file is in the same folder as my old bakup file from yesterday. Importing that file also worked. What can I do to get my library back?

Greetz from Belgium,
Edward
PS On y old Android 5.0.0 phone(which I use as FM radio)  there is no problem importing my backup file...

**Comment by nypra1314** [comment]
Well, it seems I managed to solve my problem. After many unsuccesfull tries I did this. On my old Android 5 phone I made a back-up file. Transfered this to my Nokia and succeeded importing it im BC. Happy! 
Now back to making new back-ups...

**Comment by Grunthos** [comment]
Backups are good! The latest version (6.0.2) should alleviate some of the pain in future updates and in making backups to the cloud (eg. Google Drive).

**Comment by Grunthos** [comment]
New version also no longer requires SD card access.

**Comment by nypra1314** [comment]
Thanks for taking the time to comment. Still happily using Book Catalogue.

**Comment by nypra1314** [comment]
I see in the post above there is a version 6.0.2. Where can I download that version? I still have the latest from Google PLay: 5.3.04.
