### ISSUE TITLE
Cover images are getting erased

### ISSUE THREAD

**Issue by Kallol-Mallick** [eleybourn/Book-Catalogue#872]
I successfully imported the catalogue from my old phone to a new one using backup. Everything worked very smooth. But from next day, every morning, all the cover images are lost. I can always import from backup and see all the cover images.
When the problem happens, the bookcatalogue directory is empty. Sometimes it contains a 0 byte error.log file. This folder normally contains all the jpg images after I do an import.

**Comment by Grunthos** [comment]
See our FAQ, you probably have an over-excited cleaner app:

    https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)
