### ISSUE TITLE
Goodreads integration

### ISSUE THREAD

**Issue by Imkal** [eleybourn/Book-Catalogue#874]
Hi All,

I guess The API integration with Goodreads does not work anymore looking at this annoucement https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs

I tried several times to upload my books but to no avail :(

Thanks and have a nice day,
Patrice

**Comment by Grunthos** [comment]
Grrr. Gotta love Amazon (not).

Looks like we need to start using OpenLibrary:

https://openlibrary.org/dev/docs/api/books

**Comment by Imkal** [comment]
But not a lot of French book in that Library, if any at all :(

**Comment by Grunthos** [comment]
Is there an equivalent multi-national, EU, or french source?

**Comment by Imkal** [comment]
Not that I know, the French site I know  (Babelio) is not proposing any API :(

**Comment by JeanFred** [comment]
I have seen [TheStoryGraph](https://thestorygraph.com/) touted as a Goodreads alternative ; but [there is no API support yet](https://roadmap.thestorygraph.com/features/posts/an-api) :-(

**Comment by jaymarvels** [comment]
Doesn't the announcement say no new Dev keys and current API users will still have access? So th app should still work?

**Comment by chloe5972** [comment]
Hi

Your app is fantastic !!

What about include https://www.librarything.fr as book source ???

Thanx

**Comment by jaymarvels** [comment]
> Hi
> 
> Your app is fantastic !!
> 
> What about include https://www.librarything.fr as book source ???
> 
> Thanx

It already has librarything.com integration

**Comment by Grunthos** [comment]
Unfortunately LT and GR have both disabled their APIs. We have removed support in the upcoming release (in beta). 

As a side-note, we have done some work on backup to *our* servers, but that requires a lot more time and effort to complete, and may not happen.
