### ISSUE TITLE
My ISBNs are corrupted... i think it happened when i exported to a csv but I'd love to know if they can be fixed in a batch?

### ISSUE THREAD

**Issue by JenStosser** [eleybourn/Book-Catalogue#879]

**Comment by eleybourn** [comment]
Maybe, could you email me a copy of your export.csv file and I'll have a
look.

TTFN
Evan

**Comment by Grunthos** [comment]
Also have a look at our FAQ on how to edit CSV files (avoiding importing ISBN as numeric).
