### ISSUE TITLE
LibraryThing dev key not accepted

### ISSUE THREAD

**Issue by SSSidekick** [eleybourn/Book-Catalogue#880]
I obtained a developer key from LibraryThing and tried to enter it on the LT integration page of the app and when I press the Save button it shows this error message:
![Screenshots_2022-07-11-18-33-17](https://user-images.githubusercontent.com/55944174/178388976-bd9f411f-7433-438a-ba78-a360d752fddd.png)

Is this no longer an option?

**Comment by Grunthos** [comment]
Sadly not. The LibraryThing web site reports that APIs are no longer supported. The next release has removed LT from the app.
