### ISSUE TITLE
Image database?

### ISSUE THREAD

**Issue by ctjayhawker** [eleybourn/Book-Catalogue#881]
I ask pardon for not really knowing how databases work in this context, but my query is this. 
I have a LOT of books scanned and saved in my Catalogue. Consequently, I have a lot of covers as well. In exporting my most recent backup, I notice that I have a "Covers" database file. I'm going to go out on a limb and presume that this does NOT contain all cover info somehow miraculously smooshed down into a few KB. Therefore, I am also presuming that, should I delete the hundreds of MB of cover images, that those images will be well and truly gone. Is this correct, and if so am I further correct in presuming that the only way to maintain said covers is pretty much just to leave them sit as they are? Moving these to my SD card seems like it would just cause havoc.

Thanks!

**Comment by eleybourn** [comment]
That is correct. However, you can resize them smaller if some of the cover
images are too large.

TTFN
Evan

**Comment by Grunthos** [comment]
Also, in the latest version the images are stored in a non-public folder (and moved there as part of the upgrade).

**Comment by ctjayhawker** [comment]
Hi, Evan!  It took a couple years, but I'm back. :-) I was adding a few new volumes to my library today, and unless I missed it, am I correct in thinking that BC no longer syncs with Amazon, Google, and Goodreads? The only thing I'm seeing pop up is bookcatalogue.com. That seems mighty limited compared to what was. :-\ 

---------- Original Message ----------
