### ISSUE TITLE
Thumbnails not being displayed - no Update Thumbnail option

### ISSUE THREAD

**Issue by TomPPaterson** [eleybourn/Book-Catalogue#882]
I have a new phone and synchronized with Goodreads to bring in my catalogue of books but no thumbnails are being displayed.  The wiki help mentions an "Update Thumbnails" option but I don't see that anywhere

**Comment by Grunthos** [comment]
Update thumbnails is in 'Admin & Prefs' -> 'Automatically update fields'.

If there are no thumbnails at all, then check 'Admin & Prefs'->'Booklist Preferences'->'Show Thumbnails' is checked.
