### ISSUE TITLE
Backup Problem

### ISSUE THREAD

**Issue by pschraub** [eleybourn/Book-Catalogue#884]
I am attempting to back up my database, but the app tells me that it cannot because my sd card is full or cannot be written to.
I have confirmed that my sd card is ok.
Also, my past backups are not found by the app.
Thank you in advance for your help.
Great app!

**Comment by eleybourn** [comment]
That's not good. Can you look in your internal storage (/bookCatalogue
folder) and tell me if you can see either an export.csv or
bookCatalogue-DATE.bcbk file?

TTFN
Evan

**Comment by pschraub** [comment]
Thank you for your response.

In addition to the individual book files, I have four files in the folder:
bookCataloguebookCatalogueDbExport-tmp
bookCataloguebookCatalogueDbExport-tmp.db
Export
Export.1

As a backup, I created a CSV file and emailed it to myself.

Phillip Schraub

**Comment by pschraub** [comment]
I think that I resolved my issue.
I noticed that the app was trying to create the backup in the bookcatalogue/archive folder, but the “archive” folder was not there.
I created a bookcatalogue/archive folder and the backup worked, and the backup was also listed for restore.
Do not know why the “archive” folder disappeared.

Thanks.

Phillip Schraub
