### ISSUE TITLE
Goodreads overwrite

### ISSUE THREAD

**Issue by Marianne527** [eleybourn/Book-Catalogue#886]
I use this app to keep track of books I own and have read. ( So I stop buying the same book over again!) I mistakenly clicked OK to link to Goodreads. Now I have all my Goodreads books mixed in what I have. Aside from going through 500 books and deleting them all... is there way to mass delete and restore a backup? Will that even work?  THANKS for your HELP!!! Marianne

**Comment by Grunthos** [comment]
Your best bet is (1) Do a backup in case something goes wrong (and copy it off the phone). (2) Export to CSV. (3) Edit the CSV file (see our FAQ for cautions on how to do that) and delete the rows you don't want, (4) Uninstall (and don't delete folders if it asks), (5) Reinstall (6) Import the CSV
