### ISSUE TITLE
Upgrade to 6: No upgrade message

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#892]
Google Play has upgraded the app to the latest version. I didn’t get any upgrade warning, though, as described in the FAQ…

https://github.com/eleybourn/Book-Catalogue/wiki/Frequently-Asked-Questions-(FAQ)

…which is why I tried to retrieve some covers via the “Automatically Update Fields” feature. 

After some detours, I managed to restore the original state (thanks for the e-mail support).

**Comment by Grunthos** [comment]
Can you let me know (if you recall) the versions of Android and BookCatalogue that you were upgrading From and To?

**Comment by ChristianGruen** [comment]
It was Android 13, and I used Google Play to update from the most recent version of 5 to the most recent 6 version. I tend to be sure that I didn't see the warning on any of the 3 devices I’ve used (but I’ve always seen the What’sNew dialog).

**Comment by jensberke** [comment]
I had the same problem. There was a popup showing the release notes when I started the app (the content for key `<string name="new_in_600">` from `res/values/strings.xml` ), but the message with key `<string name="old_files_message">` didn't appear.

* Android version: 11
* Current version of Book-Catalogue: 6.0.2
* Previous version of Book-Catalogue: not sure, but must have been the latest from Play Store for Android 11 (version 5.3?).

**Comment by Grunthos** [comment]
Wondering if perhaps this is a conflict between the periodic (every 5 startups) "Backup" message and the new message. So far I have not been able to reproduce this, so it suggests a more subtle issue.

**Comment by ChristianGruen** [comment]
Maybe the WARNING text should simply be added to the changelog text in order to prevent other users from losing covers.

**Comment by Grunthos** [comment]
The process that displays the warning dialog begins the steps to import the old files. It's the entire process that seems to fail (the message is just the first step). Copying the warning to the upgrade dialog would reduce the cost of failure, but a better solution is to fix it if I can.

**Comment by Grunthos** [comment]
Is it possible that you clicked the 'Back' key to exit the upgrade message? I think this may relate to your other comment about the 'back' key and the backup message.

**Comment by Grunthos** [comment]
Found it, I believe. Please tell me that you have "Start in My Books" turned on...

**Comment by ChristianGruen** [comment]
> Found it, I believe. Please tell me if you have "Start in My Books" turned on...

I do ;)

**Comment by jensberke** [comment]
Yes, I do.

**Comment by Grunthos** [comment]
Excellent. Cause found. Now I just need to fix it.

**Comment by Grunthos** [comment]
Thanks all for your help and patience with this one!

**Comment by Grunthos** [comment]
Fixed in 6.0.4
