### ISSUE TITLE
Book Catalogue 6: Backup to/Import from Archive doesn’t work

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#893]
This is what I did:

1. Pixel 5 (Android 13): Admin → Backup to Archive (appr. 4800 books)
2. Xiaomi Pad 5 (Android 13): Fresh installation of Book Catalogue via Google Play
3. bcbk files copied from Pixel to Pad
4. Admin → Import from Archive: 0 Books are listed

This worked fine with older versions of the app. Is there any other recommended way to copy collections to another device?

**Comment by Grunthos** [comment]
Can you check/confirm the size of the file once it is copied to the new device?

Can you also try to do the import then go straight to 'Help'->'Send Information'.

**Comment by ChristianGruen** [comment]
The file size (727 MB) of the source and target files is identical, as well as the generated md5 hash value. I've sent the information as requested.

**Comment by ChristianGruen** [comment]
This one feels critical. I have exported a new archive today (after I have updated some books, just for testing), and I tried to import the archive on both an Android 9 and 13 device.

In both cases, 0 books were imported, only the styles (for the arrangement of the entries, etc) were created.

![Screenshot_2023-06-22-16-10-52-380_com eleybourn bookcatalogue](https://github.com/eleybourn/Book-Catalogue/assets/196589/ae2479af-cb9c-4b81-beb7-2cad19bb81f5)
![Screenshot_2023-06-22-16-10-58-017_com eleybourn bookcatalogue](https://github.com/eleybourn/Book-Catalogue/assets/196589/a1551cf5-c7b0-444b-b6fe-0d883a798cd4)
![Screenshot_2023-06-22-16-11-03-177_com eleybourn bookcatalogue](https://github.com/eleybourn/Book-Catalogue/assets/196589/f2ad078c-9297-4643-b349-50d44d786048)
![Screenshot_2023-06-22-16-16-07-731_com eleybourn bookcatalogue](https://github.com/eleybourn/Book-Catalogue/assets/196589/2bac1218-bde8-4f50-9a23-87542eef5612)

**Comment by ChristianGruen** [comment]
> OK, this too I can not reproduce. Did you click on "All Books"?

Yes, I did.

> * Move the backup to **Android 9**
> * Run the restore on Android 9
> * When it completes (fails) go to 'Help' -> 'send Information'

Unfortunately that doesn't work at the moment (see #896 for more information).

> Also, if I send an old APK, would you be willing to install 5.0.x in your android 9 device and repeat?

Absolutely.

> Or put the bcbk somewhere that I can download it?

Should be doable.

**Comment by Grunthos** [comment]
Here is a link to the 191 APK on Google Drive:

    - https://drive.google.com/file/d/1swYH79YSEZLuBMewAFaYyVfwp-dA0CfM/view?usp=drive_link

This should be installable on both devices, but in the short term please just try Android 9, then try importing the bcbk from V6.0.2 and using 'Help'->'Send Information' if it fails.

**Comment by ChristianGruen** [comment]
…done. I have sent you the information mail (the import also fails with the version 5 you provided to me).

**Comment by ChristianGruen** [comment]
It seems the `books.csv` file in the archive has 0 bytes, so I tried to do a manual CSV export again – and it failed:

* I opened BookCatalogue 6 (the latest version) with Android 13 (Pixel 5).
* For "Admin → Import from Archive → Choose directory → "Save" I got "Export failed - could not write to the shared storage".
* I tried different target directories, but I always got the same error.

**Comment by Grunthos** [comment]
Do you have enough space on your storage? Seems like it's full and "Backup to Archive" might be silently failing.

**Comment by Grunthos** [comment]
AFAICT, "Backup to Archive" does not fail silently if it runs out of space. So...that's not likely the problem. There seems to be another issue with the export to CSV.

**Comment by Grunthos** [comment]
The problem was that (a) the code still checked if the export location was writable (it wasn't), (b) it did the check badly and (c) the place it was checking *should* have been writable, but wasn't on some devices.

This is now fixed in the latest release.

**Comment by ChristianGruen** [comment]
I can confirm it works now. Thanks for the excellent support and swift replies!
