### ISSUE TITLE
Formatting book covers

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#894]
Landscape covers take more space than expected:

![bc](https://github.com/eleybourn/Book-Catalogue/assets/196589/0f1eab77-b25e-4e5c-885e-808cf4efef89)

I imagine this was different in previous versions of the app.

**Comment by Grunthos** [comment]
Hmmm. This does look like a regression of some kind. If you have not already done so, can you go to 'Help'->'Send Information' so that we can try to reproduce on the nearest version possible?

**Comment by ChristianGruen** [comment]
I sent you a mail, I hope it arrived. It should be reproducible with any landscape cover (I have tested Android 9 and 13 devices).

**Comment by Grunthos** [comment]
Fixed in current sources, will be in 6.0.5

**Comment by ChristianGruen** [comment]
Confirmed!
