### ISSUE TITLE
Android 9: “Send information” fails

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#896]
When trying to send information with my Android 9 device, I get the popup message “Export failed - could not write to the shared storage”.

Sending messages works with my Android 13 devices.

**Comment by Grunthos** [comment]
I believe that this is fixed in the latest release (6.0.4). Can you please confirm?

**Comment by ChristianGruen** [comment]
With 6.0.4, I still get the same error with Android 9.

**Comment by Grunthos** [comment]
Fixed in current sources, will be in 6.0.5

**Comment by ChristianGruen** [comment]
Confirmed!
