### ISSUE TITLE
Admin » Preferred interface Language: Works only partially

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#897]
When changing the interface language, the main menu is presented in that language. When I close and reopen Book Catalogue, the standard language is used again (German, in my case).

When I look up the menu item for changing the language, I see that the formerly selected language is still  displayed (so the problem seems to ne that it’s not applied after a restart).

**Comment by Grunthos** [comment]
Fixed in current sources, will be in 6.0.5

**Comment by ChristianGruen** [comment]
Partially confirmed, see the screenshot. The language in the main menu is now correct, but there are other cases with different languages.

<img src="https://github.com/eleybourn/Book-Catalogue/assets/196589/893480c4-5f41-42ad-ac80-be350de4a293" width="200"/>

**Comment by Grunthos** [comment]
I think finally fixed in 6.0.6

**Comment by ChristianGruen** [comment]
Works like a breeze.
