### ISSUE TITLE
Increase enlarged image size?

### ISSUE THREAD

**Issue by ChristianGruen** [eleybourn/Book-Catalogue#898]
It would be nice if 80%, or even more, of the available screen size could be used for the enlarged image presentation.

<img src="https://github.com/eleybourn/Book-Catalogue/assets/196589/caa6fa72-b179-4efe-a8d3-833aba8a99ad" width="200"/>

**Comment by Grunthos** [comment]
In 6.0.6

**Comment by ChristianGruen** [comment]
🚀 Confirmed to work in 6.0.6. You make me happy!
