### ISSUE TITLE
"Barcode Scanner" from ZXing is no longer used to scan

### ISSUE THREAD

**Issue by ytdlder** [eleybourn/Book-Catalogue#905]
I don't know if this is a Book Catalogue (BC) issue, but I've always used this combination. Now I read that this is one of the "supported" scanning apps, which makes me hopeful that this should actually work.

But for whatever reason, BC is no longer using ZXing, but the - it seems to me - "Samsung Camera Internal" one? The thing is: it doesn't work. No barcode is scanned (maybe the internal only reacts to QR codes?).

I've already checked and the Camera setting and "Scan QR codes" is disabled!
In BC, ZXing is also selected as the scanner that should be used!

I have no idea what else I should try. Maybe the following is of use:
Samsung Galaxy A41
OneUI: 4.1
Android: 12
Kernel: 4.14.186

Thanks in advance; hopefully, we can get this working again :-)

**Comment by ChristianGruen** [comment]
> ZXing is also selected as the scanner that should be used!

Have you already tried to choose the new “Builtin Scanner”? It works fine for me.

**Comment by ytdlder** [comment]
Yes; I've tried every option. Nothing seems to work. It's always the nondescript scanning-app (there is no info what it is, so I assume it's the builtin one)

**Comment by Grunthos** [comment]
Can you perhaps send a photo of a barcode it does not scan and also, after failing to scan for a while, go to 'Help'->'Send Information'?

For me I seem to only have to wave the camera vaguely at a barcode for the scan to work and it would be good to have an example that fails often.

**Comment by ytdlder** [comment]
I've un-/installed the Zxing scanner a couple of times and made sure it was selected. but this app never opens, only the builtin.

So I guess there's 2 potential problems:
1) most importantly: why isn't BC using Zxing?
2) why isn't the internal app working (which really isn't your problem to solve^^) So why isn't the internal scanning the code? No idea, but if we could solve problem 1, then it doesn't really matter...

**Comment by ytdlder** [comment]
Well, that's a bit awkward... I've tried it right now, again, and the internal app kinda did it's thing. It scanned the code for whatever reason. Really fast too.
So... I'll close this ticket now.

Problem 1 is still unsolved, but as long as the internal app is working (lets see how long that goes), it's a non-issue.

Thanks for trying to help. I'll reopen this case (if that's possible), when I get into this trouble again.
